const { showDraft } = require('./helpers.cjs');
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_PATH || undefined });
  const errors = [];
  const base = require('./helpers.cjs').BASE;
  const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
  page.on('pageerror', e => errors.push(e.message)); page.on('console', m => { if (m.type() === 'error') errors.push('console: ' + m.text()); });
  const text = () => page.$eval('#panel', el => el.innerText);
  await page.goto(base + '?seed=42&players=4&seat=1', { waitUntil: 'networkidle' });
  await showDraft(page); await page.click('#panel .rank li:nth-child(1)');
  let t = await text(); assert.match(t, /Your pick[\s\S]*#1 of \d+ · 100% of best[\s\S]*Great pick/);
  await page.click('#keep');
  t = await text(); assert.match(t, /Your first settlement[\s\S]*#1 of \d+ · 100% of best[\s\S]*Great pick — the best open corner/);
  assert.match(t, /Your first settlement[\s\S]*Road: point it toward the \d+-pip corner/);             // R13 starting road, in words
  assert.equal(await page.$$eval('#svg line.road.me', a => a.length), 1, 'one suggested road drawn for the kept settlement');
  console.log('great first pick, verdict persists, starting road suggested');
  await page.$$eval('#svg .vx.legal', a => a[a.length - 1].dispatchEvent(new MouseEvent('click', { bubbles: true })));
  const m = (await text()).match(/Your pick\s+#(\d+) of (\d+) · (\d+)% of best\s+(\w+) pick/); assert.ok(m);
  await page.click('#keep');
  t = await text(); assert.match(t, /Your second settlement[\s\S]*% of best[\s\S]*(Great|Good|Fair|Weak) pick/); assert.match(t, /Your opening/);
  if (m[1] !== '1') assert.match(t, /What the best corner had that this lacks/);
  const url = page.url();
  await page.goto(url, { waitUntil: 'networkidle' });
  t = await text(); assert.match(t, /Your first settlement[\s\S]*Great pick[\s\S]*Your second settlement/);
  console.log('second verdict shown; both survive reload');
  await page.goto(base + '?seed=42&players=4&seat=1&best=0', { waitUntil: 'networkidle' });
  assert.equal(await page.$$eval('#svg .badge', a => a.length), 0);
  await page.$$eval('#svg .vx.legal', a => a[5].dispatchEvent(new MouseEvent('click', { bubbles: true })));
  t = await text(); assert.match(t, /Your pick\s+preview/); assert.doesNotMatch(t, /% of best|pips of production|Score \d/);
  await page.click('#keep');
  t = await text(); assert.match(t, /Your first settlement[\s\S]*% of best[\s\S]*(Great|Good|Fair|Weak) pick/);
  await page.click('#undo'); assert.doesNotMatch(await text(), /Your first settlement/);
  console.log('show-best off: preview blind (no score leak), verdict after keep, undo clears');
  await browser.close();
  assert.deepEqual(errors, [], 'page errors: ' + errors.join(' | '));
  console.log('VERDICT E2E OK, zero page errors');
})().catch(e => { console.error('E2E FAIL', e.message); process.exit(1); });
